### ISSUE TITLE
Fix canvas vfb example

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#324]
- [ ] Fix selection - Fixed on #307 
- [x] Fix 'pan home'
- [x] Fix 'Could not find icon null' warning
- [ ] Fix 'rotate z' and 'rotate mz'  -> Moved to #327 
- [ ] Clicking on empty space on the canvas seems to be re rendering when it shouldn't -> #328 
  - [ ] Fix particles not always showing -> might be related with the above

**Comment by afonsobspinto** [comment]
Escalated subtask to new issue #327 due to it's complexity

**Comment by afonsobspinto** [comment]
https://user-images.githubusercontent.com/19196034/157266010-1c2c1f35-e65f-45dc-89a4-d4587fe58e18.mp4
