### ISSUE TITLE
Prepare geppetto-ui package for integration in a new React app

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#66]
**Tasks**

* Add geppetto-ui as dependency to a new React application without using geppetto-client and geppetto-core
* Resolve any issues that might arise
* Resolve any dependency issues with React version 17.x.x
* Create bundle and compile TS to JS (example: https://github.com/ccnokes/dom-event-utils, https://github.com/Microsoft/TypeScript-Babel-Starter )
* Publish first version to npm so that we can use it in other projects

Nice overview: https://betterstack.dev/blog/npm-package-best-practices/#heading-publishing-process

Goal. the published version should work without issues in a new create-react-app project

**Known issues**

* [ ] geppetto-ui defines react and react-dom dependency with 16.x.x version. Causes Invalid Hook error when parent app has React 17.x.x. version
* [x] *@fortawesome/fontawesome-svg-core* is missing as dependency, it is present in geppetto-client and since packages are often used together this wasn't noticed so far
* [ ] TreeViewer won't work with React 17.x.x (#65)
* [ ] geppetto-ui implicitly assumes the presence of a material-ui theme together with some specific attributes such as `theme.palette.button.main` (CustomToolbar.js). That's not an issue per se, but we have to document it or provide a fallback.
